name: Release Steampipe Anywhere Components

on:
  workflow_dispatch:
        

jobs:
  anywhere_publish_workflow:
    uses: turbot/steampipe-workflows/.github/workflows/steampipe-anywhere.yml@hack
    secrets: inherit
